if ENV['RAILS_ENV'] == 'development'
  GoogleMap::GOOGLE_APPLICATION_ID = 'ABQIAAAA3HdfrnxFAPWyY-aiJUxmqRTJQa0g3IQ9GZqIMmInSLzwtGDKaBQ0KYLwBEKSM7F9gCevcsIf6WPuIQ'
else
  GoogleMap::GOOGLE_APPLICATION_ID = 'ABQIAAAA91SusluKAGjWOloL75RU6BSzCNJpVkPUOl0CP8f6M-W5Jpf0CRSJs9zvlMrNEzSuDmfcARrnM4UoZA'
end